# Generated by Django 2.1.4 on 2018-12-19 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('detail', models.TextField(max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('isWorking', models.BooleanField(default=True)),
                ('spend_weight', models.FloatField(default=0.0)),
                ('reward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('project1', models.CharField(default='无/学习', max_length=45)),
                ('weight1', models.FloatField(default=0.0)),
                ('project2', models.CharField(default='无/学习', max_length=45)),
                ('weight2', models.FloatField(default=0.0)),
                ('project3', models.CharField(default='无/学习', max_length=45)),
                ('weight3', models.FloatField(default=0.0)),
                ('detail', models.TextField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ReportToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(default='pbkdf2_sha256$120000$Ffs7kcmRo3tZ$+/nkfi0NFgJE/e1S6kWutjD8rwILcwHPGBtsZW38t74=', max_length=200)),
                ('superuser', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('last_login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login time')),
            ],
        ),
        migrations.CreateModel(
            name='UserToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Users')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Project')),
            ],
        ),
        migrations.AddField(
            model_name='reporttoproject',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Users'),
        ),
        migrations.AddField(
            model_name='reporttoproject',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Project'),
        ),
        migrations.AddField(
            model_name='reporttoproject',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Users'),
        ),
    ]
