# Generated by Django 2.1.4 on 2018-12-12 03:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('detail', models.TextField(max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('isWorking', models.BooleanField(default=True)),
                ('reward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('weight1', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(default='pbkdf2_sha256$120000$Waul9UUksVbV$mlLrZGoSrZKAO5bKvqcr8cl0WulwvIv8XI0EC/Z8ihQ=', max_length=200)),
                ('superuser', models.BooleanField(default=False)),
                ('last_login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login time')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Users'),
        ),
    ]
