# Generated by Django 2.1.4 on 2018-12-12 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='project1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Project'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$n9EWDqvujhvB$bIY7WGvRGyb0nSTFpbycCh2llJT4DvBskXQjJ53G1sE=', max_length=200),
        ),
    ]
