# Generated by Django 2.1.4 on 2018-12-20 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='join_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='users',
            name='leave_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$F7h3GlFln8LT$/Ck8JFT404nCTlaIUFn2WUB4S7vs4oS1FQx1FC0NsPo=', max_length=200),
        ),
    ]
