# Generated by Django 2.1.4 on 2018-12-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0002_auto_20181220_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttoproject',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$IL8PRXkfV6tg$Fvkg4qTR3Ygv/QT1/G4TbPvDWNtTBZLeJyVgai39m9U=', max_length=200),
        ),
    ]
