# Generated by Django 2.1.4 on 2018-12-12 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0002_auto_20181212_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='project1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='weight1',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$pef1DdJ2bByl$ceS0cpyZCj87M1f2fXXbBz/eVX+M5N4Lwnmm7PT7YP8=', max_length=200),
        ),
        migrations.AddField(
            model_name='reporttoproject',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Report'),
        ),
    ]
