# Generated by Django 2.1.4 on 2018-12-20 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0003_auto_20181220_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttoproject',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='leave_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$8BbrYKBETyB2$PUV3WYFJh8VktjLgG02xBmZ/gSGgcN+7QtZrnPNNhf4=', max_length=200),
        ),
    ]
