# Generated by Django 2.1.4 on 2018-12-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0003_auto_20181212_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='spend_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$QmqzyVSeO2br$+edFDF7mxU6rBg2OysAetfGVJIbnPJyuQykgcIA+6hk=', max_length=200),
        ),
        migrations.AddField(
            model_name='usertoproject',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Users'),
        ),
        migrations.AddField(
            model_name='usertoproject',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Project'),
        ),
    ]
