# Generated by Django 2.1.4 on 2018-12-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0004_auto_20181212_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='project1',
            field=models.CharField(default='无/学习', max_length=45),
        ),
        migrations.AddField(
            model_name='report',
            name='project2',
            field=models.CharField(default='无/学习', max_length=45),
        ),
        migrations.AddField(
            model_name='report',
            name='project3',
            field=models.CharField(default='无/学习', max_length=45),
        ),
        migrations.AddField(
            model_name='report',
            name='weight1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='report',
            name='weight2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='report',
            name='weight3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$0TXm9kDHgVhp$x8BzPhxOJTjOnkDBEt9g11bhBZLwmTctcR31w9wyHA8=', max_length=200),
        ),
    ]
