# Generated by Django 2.1.4 on 2018-12-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0005_auto_20181212_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='detail',
            field=models.TextField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$xudMTUARsblZ$RMC9Ef9p42pG7H1x1h5ilOOtaF76kpXvuwNRPnHuH3k=', max_length=200),
        ),
    ]
