# Generated by Django 2.1.4 on 2018-12-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0006_auto_20181213_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$dq2fYxf0QH56$7txno+acv5cwJy/XAY/D42uEijtnavpPp1zmrNt2YIQ=', max_length=200),
        ),
    ]
