# Generated by Django 2.1.4 on 2018-12-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0007_auto_20181213_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttoproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reporttoproject',
            name='report',
        ),
        migrations.AddField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$SSbM8FZYlO4I$wK0j+4Z4xXguWILxvzVDTm5rPFgaR/KH4qAEd/RgvDo=', max_length=200),
        ),
        migrations.DeleteModel(
            name='ReportToProject',
        ),
    ]
