# Generated by Django 2.1.4 on 2018-12-14 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0008_auto_20181214_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportToProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Project')),
                ('report', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyreport.Report')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$trqXPxh30MLb$yYRLCBSakR7U5RoSUPE9Jk7hN0SdCeaP1BxQ10nJLz8=', max_length=200),
        ),
    ]
